default: &DEFAULT
  # batch_size: 100
  # num_epoch: 1000
  # optimizer: Adam
  learning_rate: 1e-4
  dropout_rate: 0.5
  l2_regularization: 1e-8
  xentropy_label_smoothing: 0.
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8

mobilenet:
  <<: *DEFAULT
  learning_rate: 1e-5
  fine_tuning: True
