default: &DEFAULT
  train_batch_size: 32
  train_epochs: 1000
  epochs_between_evals: 100
  #hyperparameters_file: hyperparameters.yaml
  hyperparameter_set: mobilenet
  model_dir: out

gtx1080ti:
  <<: *DEFAULT
  train_batch_size: 512

thinkpadx201t:
  <<: *DEFAULT
  train_batch_size: 10
  train_epochs: 10
  epochs_between_evals: 1
  random_seed: 0